name: "asr_encoder"
backend: "onnxruntime"
max_batch_size: 8

input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [-1, 80]
  },
  {
    name: "x_lens"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [] }
  }
]

output [
  {
    name: "encoder_out"
    data_type: TYPE_FP32
    dims: [-1, 512]
  },
  {
    name: "encoder_out_lens"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [] }
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 5000
}

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
