name: "asr_feature"
backend: "python"
max_batch_size: 8

input [
  {
    name: "WAV"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "WAV_LEN"
    data_type: TYPE_INT32
    dims: [1]
  }
]

output [
  {
    name: "SPEECH"
    data_type: TYPE_FP32
    dims: [-1, 80]
  },
  {
    name: "SPEECH_LEN"
    data_type: TYPE_INT64
    dims: [1]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 4
  }
]

parameters {
  key: "max_frames"
  value: { string_value: "1600" }
}
